import { Injectable, NotFoundException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { EventType } from '../../common/enums';
import { MatchExplanationDto, RequirementInsightsDto } from '../../common/api-dtos';
import { SampleStoreService, VendorRecord } from '../../common/sample-store.service';

@Injectable()
export class AiService {
  constructor(
    private readonly config: ConfigService,
    private readonly store: SampleStoreService,
  ) {}

  analyzeRequirementText(text: string): RequirementInsightsDto {
    const normalized = text.toLowerCase();
    const eventType = this.extractEventType(normalized);
    const city = this.extractCity(normalized);
    const budget = this.extractBudget(normalized);
    const guestCount = this.extractGuestCount(normalized);
    const eventDate = this.extractDate(text);
    const theme = this.extractTheme(normalized, eventType);
    const suggestedServices = this.suggestServices(eventType, theme);

    return {
      eventType,
      city,
      budget,
      guestCount,
      theme,
      eventDate,
      suggestedServices,
      notes: this.buildRequirementNotes(guestCount, theme, suggestedServices),
    };
  }

  explainMatch(requirementId: string, vendorId: string): MatchExplanationDto {
    const requirement = this.store.findRequirement(requirementId);
    const vendor = this.store.vendors.find((item) => item.id === vendorId);

    if (!vendor) {
      throw new NotFoundException(`Vendor ${vendorId} not found`);
    }

    const signals = this.collectSignals(vendor, requirement.city, requirement.budget, requirement.eventDate, requirement.theme);
    const aiProvider = this.config.get<string>('OPENAI_API_KEY') ? 'OpenAI-ready' : 'local rules';

    return {
      vendorId,
      explanation: `${vendor.businessName} is recommended because ${this.humanizeSignals(signals)}. Explanation generated by ${aiProvider}.`,
      signals,
    };
  }

  generateRecommendationReason(vendor: VendorRecord, signals: string[]): string {
    return `${vendor.businessName}: ${this.humanizeSignals(signals)}.`;
  }

  private extractEventType(text: string): EventType {
    if (text.includes('birthday')) return EventType.Birthday;
    if (text.includes('engagement')) return EventType.Engagement;
    if (text.includes('corporate')) return EventType.CorporateEvent;
    if (text.includes('baby shower')) return EventType.BabyShower;
    if (text.includes('reception')) return EventType.Reception;
    return EventType.Wedding;
  }

  private extractCity(text: string): string {
    const knownCities = ['chennai', 'coimbatore', 'kanchipuram', 'pondicherry', 'bangalore', 'hyderabad', 'mumbai', 'delhi'];
    return knownCities.find((city) => text.includes(city)) ?? 'chennai';
  }

  private extractBudget(text: string): number {
    const budgetMatch = text.match(/(?:budget|rs|inr|₹)\s*(?:is\s*)?([0-9,]+)/i) ?? text.match(/([0-9,]+)\s*(?:budget|rs|inr|₹)/i);
    return budgetMatch ? Number(budgetMatch[1].replace(/,/g, '')) : 500000;
  }

  private extractGuestCount(text: string): number {
    const guestMatch = text.match(/([0-9,]+)\s*(?:guests|people|persons|pax)/i);
    return guestMatch ? Number(guestMatch[1].replace(/,/g, '')) : 100;
  }

  private extractDate(text: string): string {
    const isoMatch = text.match(/\d{4}-\d{2}-\d{2}/);
    if (isoMatch) return isoMatch[0];

    const readableMatch = text.match(/(\d{1,2})\s+(january|february|march|april|may|june|july|august|september|october|november|december)\s+(\d{4})/i);
    if (!readableMatch) return new Date().toISOString().slice(0, 10);

    const month = new Date(`${readableMatch[2]} 1, ${readableMatch[3]}`).getMonth() + 1;
    return `${readableMatch[3]}-${String(month).padStart(2, '0')}-${readableMatch[1].padStart(2, '0')}`;
  }

  private extractTheme(text: string, eventType: EventType): string {
    const themeHints = ['traditional south indian', 'temple theme', 'floral', 'modern', 'luxury', 'candid', 'minimal'];
    const hits = themeHints.filter((hint) => text.includes(hint));
    return hits.length > 0 ? hits.join(' ') : eventType.replace('_', ' ');
  }

  private suggestServices(eventType: EventType, theme: string): string[] {
    const services = ['event_planner'];
    if ([EventType.Wedding, EventType.Engagement, EventType.Reception].includes(eventType)) {
      services.push('decorator', 'photographer', 'makeup_artist');
    }
    if (theme.includes('floral') || theme.includes('temple')) {
      services.push('flower_designer');
    }
    if (eventType === EventType.Birthday || eventType === EventType.CorporateEvent) {
      services.push('caterer', 'dj', 'photographer');
    }
    return [...new Set(services)];
  }

  private buildRequirementNotes(guestCount: number, theme: string, services: string[]): string[] {
    const notes = [`Suggested vendor categories: ${services.join(', ')}.`];
    if (guestCount >= 300) notes.push('Large guest count requires vendors with high-capacity event experience.');
    if (theme.includes('temple')) notes.push('Theme suggests decorators with mandap, floral, and traditional ceremony experience.');
    return notes;
  }

  private collectSignals(vendor: VendorRecord, city: string, budget: number, eventDate: string, theme?: string): string[] {
    const signals = [];
    const normalizedTheme = theme?.toLowerCase() ?? '';
    if (vendor.cities.includes(city.toLowerCase())) signals.push('location_match');
    if (budget >= vendor.priceMin && budget <= vendor.priceMax) signals.push('budget_match');
    if (vendor.availableDates.includes(eventDate)) signals.push('availability_match');
    if (vendor.rating >= 4.5) signals.push('high_rating');
    if (vendor.responseRate >= 85) signals.push('fast_response');
    if (vendor.specializations.some((item) => normalizedTheme.includes(item) || item.includes(normalizedTheme))) signals.push('theme_match');
    return signals.length > 0 ? signals : ['partial_match'];
  }

  private humanizeSignals(signals: string[]): string {
    const labels: Record<string, string> = {
      location_match: 'it serves the event city',
      budget_match: 'it fits the stated budget',
      availability_match: 'it is available on the event date',
      high_rating: 'it has strong customer ratings',
      fast_response: 'it has a high response rate',
      theme_match: 'it matches the requested theme',
      partial_match: 'it has a partial fit based on available vendor signals',
    };
    return signals.map((signal) => labels[signal] ?? signal).join(', ');
  }
}
